# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - development
      - main
  paths:
    exclude:
      - monitoring/*
      - README.md
      - catalog-info.*
      - .chr_meta/*
      - docs/*
      - mkdocs.*

pr:
  branches:
    include:
      - development
      - main
  paths:
    exclude:
      - monitoring/*
      - README.md
      - catalog-info.*
      - .chr_meta/*
      - docs/*
      - mkdocs.
pool:
  vmImage: windows-latest

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false
- task: PublishBuildArtifacts@1
